// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCclOjV_FdvQ1VPc-tGCji0KgF4H2Rmkcs',
    appId: '1:416231278978:android:fc34e772f7b71a1ce1e79b',
    messagingSenderId: '416231278978',
    projectId: 'chat-c2e7f',
    databaseURL: 'https://chat-c2e7f-default-rtdb.firebaseio.com',
    storageBucket: 'chat-c2e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj1y1QPr5UMS8j9bwdTQKvB0VejgOi3oU',
    appId: '1:416231278978:ios:d2be056bfba3bbfee1e79b',
    messagingSenderId: '416231278978',
    projectId: 'chat-c2e7f',
    databaseURL: 'https://chat-c2e7f-default-rtdb.firebaseio.com',
    storageBucket: 'chat-c2e7f.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );
}
